### ISSUE TITLE
Neue Methode GetInnerRingsCount()

### ISSUE THREAD

**Issue by olivergrimm** [GeoWerkstatt/geow-interlis-functions#11]
Zählt die Löcher innerhalb einer Fläche

`FUNCTION GetHolesCount (Objects: OBJECTS OF ANYCLASS; AreaAttr: TEXT): NUMERIC;`

**Comment by Philippluca** [comment]
INTERLIS erlaubt sich selbst berührende äussere Ringe. Aus der Diskussion mit Patrick ging hervor, dass die Funktion jedoch einfach innere Ringe zählen soll. Falls wir Ringe zählen wollen, schlage ich vor die Funktion `GetRingsCount` zu benennen. Mit der Subtraktion von 1 erhält man dann die "inneren" Ringe.
