### ISSUE TITLE
Neue Methode IsInsideExternalDataset()

### ISSUE THREAD

**Issue by olivergrimm** [GeoWerkstatt/geow-interlis-functions#13]
Ermittelt, ob ein Geometrieobjekt innerhalb eines anderen Objektes liegt, wobei
• das umfassende Objekt bzw. die umfassenden Objekte mit Hilfe des Datensatz-Namens sowie der Object-IDs und Geometry aus einer Transferdatei gelesen wird.
• das zu prüfende Objekt mittels TestObject und dem entsprechenden Geometriefeld bekannt gemacht wird.
• Die für die Prüfung herbeigezogenen Geometrieobjekte werden im Format XTF in einer separaten Geometrie-JAR-Datei bereitgestellt.6 / 8
• Wird keine Geometrie-JAR-Datei gefunden, sucht die Custom Function eine lokaleT ransferdatei.

Die Funktion isInside() kann so mit jedem beliebigen Datensatz eingesetzt werden. Es können auch verschiedene Transferdateien vorliegen, welche in unterschiedlichen Constraints unterschiedlich verwendet werden. Die Interpretation des korrekten Datensatzes erfolgt über den Datensatz-Namen (erster Methoden-Parameter).

Die unterstützten Geometrieoperationen sind «Fläche in Fläche», «Punkt in Fläche» oder «Linie in
Fläche» wobei Objekte, welche die Testgeometrie überlappen, als ungültig erkannt werden müssen. (Innerhalb und deckungsgleich/auf dem Rand sind als gültig zu evaluieren)

Die aus der Transferdatei interpretierten Datensätze werden in der laufenden validator-Instanz gecacht, so dass sie nur einmal gelesen werden müssen.

`FUNCTION IsInsideExternalDataset (DatasetName: TEXT; Objects: TEXT; TestObject: OBJECT OF ANYCLASS; TestObjectgeometry: TEXT): BOOLEAN;`

**Comment by Philippluca** [comment]
Vorschlag zur Reformulierung:
```
FUNCTION IsInside (Objects: OBJECTS OF ANYCLASS; Attr: TEXT, Bondries: OBJECT OF Boundary): BOOLEAN;

STRUCTURE Boundary=
 Geometrie: SURFACE;
END Boundary;
```

So können die TestObjekte in separatem xtf oder im kompletten Datensatz mitgeliefert werden.
Sollten die Daten direkt mit dem Plug-In ausgeliefert werden, dann sollten diese über eine Erweiterung am ilivalidator geladen werden können. Stichwort: Basisdaten-Plugin
