### ISSUE TITLE
Datasets mit Geometrie-Strukturen

### ISSUE THREAD

**Issue by edigonzales** [GeoWerkstatt/geow-interlis-functions#27]
Wenn man Geometrie-Strukturen (CHBase-Gedöns) verwendet, funktioniert es glaubs nicht. Ich verwende eine "GeometryCHLV95_V1.MultiSurface" im Referenzdatensatz und Fehlermeldung:

```
Warning: line 247: SO_AGI_MOpublic_20190424.MOpublic.Fixpunkt: tid 07522e68-af11-468f-84d9-0c2dac43d49e: GeoW_FunctionsExt.IsInsideExternalDataset: IoxException, unexpected Type GeometryCHLV95_V1.MultiSurface; MULTISURFACE expected
```

Vielleicht könnte man als erstes einfach die Unterstützung von CHBase-Geometrien implementieren (dazu gibt es schon bei Claude irgendwo Code, um diese zu finden). Müsste aber Interlis 2.3 kompatibel sein btw.

Siehe Anhang mit Config, Daten etc.

[Archive.zip](https://github.com/GeoWerkstatt/geow-interlis-functions/files/12440194/Archive.zip)

**Comment by olivergrimm** [comment]
Die Umsetzung soll für 2.3 erfolgen.
