### ISSUE TITLE
Lookup in BAGs

### ISSUE THREAD

**Issue by olivergrimm** [GeoWerkstatt/geow-interlis-functions#50]
Mittels einem Mandatory Constraint soll geprüft werden, ob ein spezifischer Eintrag in einer BAG vorliegt:

`MANDATORY CONSTRAINT WHERE DEFINED (Schifffahrtszeichen): Massnahmen->Reference->Schifffahrtszeichen == #true;`

Die entsprechende Klasse ist:
```
CLASS Instandsetzung EXTENDS Erfassung =
  /** SH: Zwingende Angabe wenn kein Beobachtungsstatus */
  Massnahmen : BAG {1..*} OF SH_Binnenschifffahrt_V1_0.Codeliste.Massnahmen_CodeRef;
...
```

Das Strukturelement ist in diesem Beispiel wie folgt aufgebaut:
```
CLASS Massnahmen_Code EXTENDS CatalogueObjects_V1.Catalogues.Item =
      /** Attribute werden aus bestehendem Katalog importiert */
      Massnahmen : MANDATORY TEXT*50;
      /** Optional */
      Beschreibung : TEXT*200;
      /** Zwingende Massnahmenzuordnung */
      Wiffe : MANDATORY BOOLEAN;
      /** Zwingende Massnahmenzuordnung */
      Boje : MANDATORY BOOLEAN;
      /** Zwingende Massnahmenzuordnung */
      Anlegepfahl : MANDATORY BOOLEAN;
      /** Zwingende Massnahmenzuordnung */
      Schifffahrtszeichen : MANDATORY BOOLEAN;
      !!@ ilivalid.msg_de = "Verletzt Eindeutigkeit {Massnahmen}"
      UNIQUE Massnahmen;
END Massnahmen_Code;

STRUCTURE Massnahmen_CodeRef
    EXTENDS CatalogueObjects_V1.Catalogues.CatalogueReference =
	    /** Lediglich ein Hilfsmittel */
      Reference (EXTENDED) : MANDATORY REFERENCE TO (EXTERNAL) Massnahmen_Code;
END Massnahmen_CodeRef;
```

**Comment by olivergrimm** [comment]
**Entwicklung einer zusätzlichen Funktion (FilterBagByCriteria o.ä.):**
Ermöglicht die Filterung von BAG oder LIST OF Attributen. Auf den Return-Elementen kann dann mittels elementCount() geprüft werden.

**Input-Parameter:**
Ausgangsobjekt: BAG-Element (im Beispiel Attribut 'Massnahmen')
Pfad zum prüfenden Attribut: (im Beispiel: >Reference->Schifffahrtszeichen)
Erwarteter Wert: (im Beispiel #true)

**Return:**
Gefiltertes BAG-Element

**Comment by Philippluca** [comment]
Toll wäre eine allgemeine `Filter`-Funktion. Ich denke man könne dann ein WHERE in INTERLIS Syntax als TEXT mitgeben.
```
MANDATORY CONSTRAINT INTERLIS.ObjectCount(Filter(THIS->Massnahmen->Reference->Schifffahrtszeichen, "WHERE THIS == #true)) >= 1
```
oder 
```
MANDATORY CONSTRAINT INTERLIS.ObjectCount(Filter(THIS->Massnahmen->Reference, "WHERE Schifffahrtszeichen == #true)) >= 1
```

**Comment by domi-b** [comment]
Eine Filter-Funktion mit beliebiger INTERLIS-Syntax wäre vielseitiger einsetzbar als ein strikter Vergleich mit `==`, hat aber auch eine deutlich höhere Komplexität.
Eventuell lässt sich mit ili2c auch eine einzelne Expression parsen, ansonsten wird eine solche Umsetzung schwierig.
